version: "3"

services:
  ros-astra:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    privileged: true
    image: ros_astra_camera
    container_name: ros_astra_camera
    command:
      [
        "bash",
        "-c",
        "source /opt/ros/ros_ws/devel/setup.bash && export ROS_MASTER_URI=http://127.0.0.1:11311 && roslaunch /opt/ros/ros_ws/src/ros_astra_camera/launch/astra.launch",
      ]
    devices:
      - /dev/ttyACM0
    # network_mode: host

