version: "2.3"

services:
  # ROS Melodic
  astra:
    build:
      context: ../../../  
      dockerfile: ./Dockerfile
    devices:
      - /dev/ttyUSB0
    tty: true        # docker run -t
    command: roslaunch ros_astra_camera astra.launch

  # ROS Noetic + ROS 2 Foxy
  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      - "ROS_MASTER_URI=http://astra:11311"
    command: ros2 run ros1_bridge dynamic_bridge

  # ROS 2 Foxy
  rviz-nvidia:
    image: husarion/rviz2-rosbot:latest
    runtime: nvidia    
    environment: 
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config.rviz:/root/.rviz2/default.rviz
    command: ros2 run rviz2 rviz2