# Quick Start
# just plug Orbbec Astra to your laptop and launch:
# $ docker compose up

services:
  astra:
    image: husarion/astra:humble
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    network_mode: host
    ipc: host
    devices:
      - /dev/bus/usb/
    volumes:
      - ./astra_params.yaml:/ros2_ws/install/astra_camera/share/astra_camera/params/astra_mini_params.yaml
    command: ros2 launch astra_camera astra_mini.launch.py

  rviz:
    image: husarion/rviz2:humble
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
